name: デプロイ

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Node.js セットアップ
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: 依存関係インストール
        run: npm ci
        
      - name: ビルド
        run: npm run build
        
      - name: GitHub Pages デプロイ
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
        